app/controllers/application_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
users can enter name on sign up
added devise views too
=> added name to signup

app/controllers/bookings_controller.rb, app/controllers/courses_controller.rb, app/controllers/teacher/courses_controller.rb, app/views/bookings/create.html.erb, app/views/bookings/delete.html.erb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/bookings/update.html.erb, app/views/courses/create.html.erb, app/views/courses/delete.html.erb, app/views/courses/edit.html.erb, app/views/courses/index.html.erb, app/views/courses/new.html.erb, app/views/courses/show.html.erb, app/views/courses/update.html.erb, app/views/teacher/courses/index.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/controllers/courses_controller_test.rb
I added initial needed routes and corresponding controllers and views.
=> add initial routes

Gemfile, Gemfile.lock, User.first, app/models/booking.rb, app/models/course.rb, app/models/user.rb, db/migrate/20250118094034_create_courses.rb, db/migrate/20250118095339_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/course_test.rb
Finally generated all the models with the correct relationships among them.
=> Generate models

Gemfile, Gemfile.lock, app/controllers/courses_controller.rb, app/models/course.rb, app/models/user.rb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, db/seeds.rb
all seeds are done (users, courses, bookings)
=> Make index pg

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb
=> simple bookings page, can view course and destroy booking. will add more features laters >:)

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_footer.scss, app/assets/stylesheets/pages/_home.scss
I made the landing page into one page and made sure there is no scroll bar
=> make landing page in one page and remove scroll bar

app/assets/stylesheets/application.scss, app/assets/stylesheets/pages/_index.scss, app/views/courses/index.html.erb, app/views/courses/show.html.erb
I adjusted the banner to responsive design
=> responsive design for banner on course-index page

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/courses/index.html.erb, app/views/courses/show.html.erb
just made some adjust to index card
=> adjust index card

app/assets/stylesheets/pages/_home.scss, app/controllers/bookings_controller.rb, app/views/courses/show.html.erb, app/views/pages/_navbar.html.erb
made changes to navbar login button
=> landing page nav bar login button add

app/assets/stylesheets/pages/_index.scss, app/views/courses/show.html.erb
=> Backup master

app/controllers/bookings_controller.rb, app/views/layouts/application.html.erb
=> create btn works

app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/_navbar.html.erb
added the log in, sign up functionality in navbar.
=> log in, sign up functionality in navbar

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_show.scss, app/views/bookings/index.html.erb, app/views/pages/_navbar.html.erb
change the navbar and booking page
=> change navbar

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/bookings_controller.rb, app/models/course.rb, app/views/courses/_card.html.erb, app/views/courses/index.html.erb, app/views/courses/new.html.erb, app/views/layouts/application.html.erb, db/migrate/20250127034650_add_categoryto_courses.rb, db/schema.rb, db/seeds.rb
1. I just changed layout of cards and delete the p tag for notice in landing page
2. background color of cards will change with category
3. add a new column "category" to course model and schema
=> edit cards layout in course index page

app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index.scss, app/views/courses/index.html.erb
=> change the font

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/_show.scss, app/views/courses/show.html.erb
1. change the layout and design of the course show page
2. add recommendation list of courses that the user may like
=> change the layout and design of course show page

app/controllers/courses_controller.rb, app/views/courses/edit.html.erb, app/views/courses/new.html.erb, app/views/courses/show.html.erb, app/views/pages/_navbar.html.erb
"added course updating feature, modified course controller and update course view, added a modify course link on show page only if you are the teacher of that course"
=> Favorites controller views

app/assets/stylesheets/pages/_teacher_course.scss, app/controllers/courses_controller.rb, app/views/bookings/update.turbo_stream.erb
little change to the approval list
=> changes to booking

app/assets/stylesheets/pages/_teacher_course.scss, app/controllers/teacher/courses_controller.rb, app/models/booking.rb, app/views/bookings/update.turbo_stream.erb, app/views/teacher/courses/index.html.erb
=> change the order of signups

app/views/bookings/index.html.erb
=> change my booking layout

app/views/bookings/index.html.erb
a small change of booking page
=> small change

app/assets/stylesheets/pages/_show.scss, app/assets/stylesheets/pages/_teacher_course.scss, app/views/courses/show.html.erb
=> change syllabus

app/models/user.rb, app/views/devise/registrations/edit.html.erb
changed avatar-default filename that was causing the trouble at heroku
=> changed avatar-default filename that was causing the trouble at heroku
